apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quantu-app-api.fullname" . }}-environment
  labels:
    {{- include "quantu-app-api.labels" . | nindent 4 }}
data:
{{ toYaml .Values.env | indent 2 }}