replicas:
  min: 1
  max: 4
  resource:
    cpu:
      utilization: 90

image:
  repository: docker.pkg.github.com/quantu-app/quantu-app-api/quantu-app-api
  tag: 0.1.0
  pullPolicy: Always
  hash: sha256:13ba025b6c186da3fdce3db68f192721fef8300ae02f2ae76c953d771b7180e4

env:
  MIX_ENV: prod

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/secure-backends: "true"
  hosts:
    - host: api.quantu.app
      paths:
        - /
  tls:
    - secretName: api-quantu-app-tls
      hosts:
        - api.quantu.app

resources:
  requests:
    cpu: 800m
    memory: 100M
  limits:
    cpu: 1000m
    memory: 1000M

postgresql:
  persistence:
    enabled: true
    storageClass: linode-block-storage-retain
  postgresqlUsername: postgres
  postgresqlPassword: postgres
