replicas:
  min: 1
  max: 4
  resource:
    cpu:
      utilization: 90

image:
  repository: ghcr.io/quantu-app/quantu-app-api/quantu-app-api
  tag: 0.1.0
  pullPolicy: Always
  hash: sha256:13ba025b6c186da3fdce3db68f192721fef8300ae02f2ae76c953d771b7180e4

env:
  MIX_ENV: prod

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt
    nginx.ingress.kubernetes.io/secure-backends: "true"
  hosts:
    - host: api.quantu.app
      paths:
        - /
  tls:
    - secretName: api-quantu-app-tls
      hosts:
        - api.quantu.app

resources:
  requests:
    cpu: 800m
    memory: 100M
  limits:
    cpu: 1000m
    memory: 1000M

postgresql:
  persistence:
    enabled: true
    storageClass: linode-block-storage-retain
    existingClaim: pvc-0d9c90ae6f1c4181
  postgresqlUsername: postgres
  postgresqlPassword: postgres
