name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24"
          elixir-version: "1.12.2"
      - uses: azure/setup-helm@v1
      - env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG }}
        run: |
          echo $KUBECONFIG_BASE64 | base64 -di > $RUNNER_TEMP/kubeconfig.yaml
          echo "KUBECONFIG=$RUNNER_TEMP/kubeconfig.yaml" >> $GITHUB_ENV
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}
      - run: MIX_ENV=prod mix helm
