name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24"
          elixir-version: "1.12.2"
      - uses: azure/setup-helm@v1
      - env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG }}
        run: |
          echo $KUBECONFIG_BASE64 | base64 -di > $RUNNER_TEMP/kubeconfig.yaml
          echo "KUBECONFIG=$RUNNER_TEMP/kubeconfig.yaml" >> $GITHUB_ENV
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}
      - env:
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          GUARDIAN_TOKEN: ${{ secrets.GUARDIAN_TOKEN }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
          FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        run: MIX_ENV=prod mix helm
